# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class juQingItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class xiJuItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class dongZuoItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class aiQingItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class keHuanItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class dongHuaItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class xuanYiItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class jinSongItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class kongBuItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class jiLuItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class duanPianItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class qingSeItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class tongXingItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class yinYueItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class geWuItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class jiaTingItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class erTongItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class zhuanJiItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class liShiItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class zhanZhenItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class fanZuiItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class xiBuItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class qiHuanItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class maoXianItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class zaiNanItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class wuXiaItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class guZhuangItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class yunDongItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()
class heiSeItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    filmName=scrapy.Field()
    scores=scrapy.Field()
    rank=scrapy.Field()
    href=scrapy.Field()
    href2=scrapy.Field()
    href3=scrapy.Field()
    href4=scrapy.Field()
    href5=scrapy.Field()
    href6=scrapy.Field()
    href7=scrapy.Field()
    weishu=scrapy.Field()